### ISSUE TITLE
The plugin cannot be installed on Ubuntu Linux despite the official support of Swift and sourcekit-lsp.

### ISSUE THREAD

**Issue by Ant01n3** [sublimelsp/LSP-SourceKit#2]
Thank you for this plugin that works perfectly on mac. However despite the fact Ubuntu Linux is officially supported by Swift, the plugin restricts its usage to macOS.

Before the 1.5.0 version of LSP, the default configuration for sourcekit allowed to use it simply by indicating in the settings that the command to use is `sourcekit-lsp`. This is no more possible, and this plugin must be installed instead. However this is possible only on a mac (package control won´t show it under Ubuntu Linux).

Would it be possible to mark this plugin as available on Linux so that package control can find it and install it ?

Also this packages tests the presence of `xcrun` which is not available on non mac-platforms where the command used to run the lsp server is `sourcekit-lsp`.

Thanks a lot

**Comment by rwols** [comment]
This seems like something implementable. Thanks for the heads up!

**Comment by rwols** [comment]
Actually, can't you just override the `"command"` in the settings (via Preferences: LSP-SourceKit Settings in the command palette)?

**Comment by rwols** [comment]
If that's documented in the readme, and we enable it for Linux, that should be enough to get people set up on linux.

**Comment by rwols** [comment]
Ah, no, we're checking if `xcrun` exists as well, as you have already noted.

**Comment by Ant01n3** [comment]
Thanks a lot, looking at the commit it should work when overriding only the `command`.
